### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by kacedali** [QoboLtd/project-template-cakephp#312] opened 2017-08-14 19:49 UTC
hi,
i have this error when i active debug mode
Warning (2): error_log(/tmp/menu.log): failed to open stream: No such file or directory [ROOT\vendor\qobo\cakephp-menu\src\MenuBuilder\MenuItemFactory.php, line 54]

correct this in \src\Template\Layout\adminlte.ctp
<script src="/admin_l_t_e/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="/admin_l_t_e/js/app.min.js"></script>

**Comment by mamchenkov** [comment] 2017-08-15 10:19
@kacedali yup, that was a little leftover in the menu plugin, which we fixed and released yesterday.

Here's the PR - https://github.com/QoboLtd/cakephp-menu/pull/70/files#diff-5820abc1424ca4ffdbab32be07caed06

The fix is in the [cakephp-menu v9.2.0](https://github.com/QoboLtd/cakephp-menu/releases/tag/v9.2.0).   If you just do `composer update` in your project, things should work properly again.

Thanks for reporting!

Please close this issue if the problem is resolved for you, or let me know if it still persists.

**Closed** 2017-08-15 10:36 UTC
